### ISSUE TITLE
updatePackage giving errors

### ISSUE THREAD

**Issue by drtinaz** [kwindrem/SetupHelper#81]
I pulled the updated SetupHelper to my developement PC (was previous v7.0), and now when I run updatePackage "packagenamehere" I get the following:

./updatePackage: line 2: $'\r': command not found
./updatePackage: line 38: $'\r': command not found
./updatePackage: line 89: $'\r': command not found
./updatePackage: line 93: $'\r': command not found
./updatePackage: line 94: $'\r': command not found
./updatePackage: line 101: $'\r': command not found
./updatePackage: line 105: $'\r': command not found
./updatePackage: line 109: $'\r': command not found
./updatePackage: line 113: syntax error near unexpected token `elif'
'/updatePackage: line 113: `elif [ ! -e "$stockFiles" ]; then

**Comment by kwindrem** [comment]
All except the last of these are blank lines and the \r suggests an end of line issue in converting from unix text files to Windows.

I and not all that familiar with what is supposed to happen during the transfer. I'm wondering that since the file doesn't have an extension maybe Windows can't deal with it. 

If adding .sh at the end (updatePackage.sh) helps let me know.

**Comment by drtinaz** [comment]
You know now that you mentioned eol, I forgot that I needed to change from CRLF to LF last time I loaded it onto my development PC. Man that gets me every time.

**Comment by kwindrem** [comment]
Glad that was it.
